flags: {}
extra-package-dbs: []
packages:
- .
- location:
    # git: git@bitbucket.org:nrink/statefulness
    # commit: 8e218ce6f4d0d54e5ee4048d2e0f6c3d9055e32f
    ../statefulness # for debugging only
  extra-dep: true
- location:
    git: git@github.com:ohua-dev/ohua-core
    commit: 868cfd3449515f38e3d9546578309af1b2bbf19f
  extra-dep: true
extra-deps:
- thrift-0.10.0
- named-0.2.0.0
- ghc-datasize-0.2.0
- ghc-heap-view-0.5.10
resolver: lts-10.4
#resolver: lts-9.21 # necessary for using datasize and heap-view
allow-newer: true
