flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: git@bitbucket.org:nrink/statefulness
    commit: 6db6c98db91f6b070b61247eeb2e3aeea9922ec5
    #commit: 947a71592a6b278d86dddab2f7191156bc2c849d
    #../statefulness # for debugging only
  extra-dep: true
- location:
    git: git@github.com:ohua-dev/ohua-core
    commit: 868cfd3449515f38e3d9546578309af1b2bbf19f
  extra-dep: true
extra-deps:
- thrift-0.10.0
resolver: lts-10.4
allow-newer: true
