flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- aeson-1.2.3.0
- primitive-0.5.4.0
- th-abstraction-0.2.6.0
- thrift-0.10.0
- transformers-0.5.5.0
- transformers-compat-0.5.1.4
- vector-0.10.12.2
resolver: lts-6.35
