{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.9.3)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module KeyValueStore_Client(requests) where
import qualified Data.IORef as R
import Prelude (($), (.), (>>=), (==), (++))
import qualified Prelude as P
import qualified Control.Exception as X
import qualified Control.Monad as M ( liftM, ap, when )
import Data.Functor ( (<$>) )
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Hashable as H
import qualified Data.Int as I
import qualified Data.Maybe as M (catMaybes)
import qualified Data.Text.Lazy.Encoding as E ( decodeUtf8, encodeUtf8 )
import qualified Data.Text.Lazy as LT
import qualified GHC.Generics as G (Generic)
import qualified Data.Typeable as TY ( Typeable )
import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet as Set
import qualified Data.Vector as Vector
import qualified Test.QuickCheck.Arbitrary as QC ( Arbitrary(..) )
import qualified Test.QuickCheck as QC ( elements )

import qualified Thrift as T
import qualified Thrift.Types as T
import qualified Thrift.Arbitraries as T


import Kvservice_Types
import KeyValueStore
seqid = R.newIORef 0
requests :: (T.Transport t0, T.Transport a2, T.Protocol a1, T.Protocol a0) => (a0 t0, a1 a2) -> Vector.Vector KVRequest -> P.IO (Vector.Vector KVResponse)
requests (ip,op) arg_reqs = do
  send_requests op arg_reqs
  recv_requests ip
send_requests :: (T.Protocol a1, T.Transport a2) => a1 a2 -> Vector.Vector KVRequest -> P.IO ()
send_requests op arg_reqs = do
  seq <- seqid
  seqn <- R.readIORef seq
  T.writeMessageBegin op ("requests", T.M_CALL, seqn)
  write_Requests_args op (Requests_args{requests_args_reqs=arg_reqs})
  T.writeMessageEnd op
  T.tFlush (T.getTransport op)
recv_requests ip = do
  (fname, mtype, rseqid) <- T.readMessageBegin ip
  M.when (mtype == T.M_EXCEPTION) $ do { exn <- T.readAppExn ip ; T.readMessageEnd ip ; X.throw exn }
  res <- read_Requests_result ip
  T.readMessageEnd ip
  P.return $ requests_result_success res
